WITH N AS (
    SELECT
        BOOK_ID,
        SUM(SALES) AS SUM_SALES
    FROM BOOK_SALES
    WHERE YEAR(SALES_DATE) = 2022
      AND MONTH(SALES_DATE) = 1
    GROUP BY BOOK_ID
)

SELECT
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(N.SUM_SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK B JOIN AUTHOR A
        ON B.AUTHOR_ID = A.AUTHOR_ID
    JOIN N
        ON B.BOOK_ID = N.BOOK_ID
GROUP BY
  A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC