WITH S AS (
    SELECT
        CART_ID,
        GROUP_CONCAT(DISTINCT NAME) AS STR
    FROM CART_PRODUCTS
    GROUP BY CART_ID
)

SELECT
    CART_ID
FROM S
WHERE STR LIKE '%Milk%'
    AND STR LIKE '%Yogurt%'
ORDER BY CART_ID