WITH RECURSIVE HOURS AS (
    SELECT 0 AS h
    UNION ALL
    SELECT h + 1 FROM HOURS WHERE h < 23
)

SELECT
    H.h AS HOUR,
    COUNT(A.ANIMAL_ID) AS `COUNT`
FROM HOURS H LEFT JOIN ANIMAL_OUTS A
    ON H.h = HOUR(A.DATETIME)
GROUP BY HOUR
ORDER BY HOUR;