SELECT
    I1.ID,
    N.FISH_NAME,
    I1.LENGTH
FROM FISH_INFO I1
    JOIN (
        SELECT
            FISH_TYPE,
            MAX(LENGTH) AS MLEN
        FROM FISH_INFO
        GROUP BY FISH_TYPE
    ) I2
    ON I1.FISH_TYPE = I2.FISH_TYPE
        AND I1.LENGTH = I2.MLEN
    JOIN FISH_NAME_INFO N
    ON I1.FISH_TYPE = N.FISH_TYPE